<?php

declare(strict_types=1);

namespace App\Policies;

use Illuminate\Foundation\Auth\User as AuthUser;
use Spatie\Permission\Models\Role;
use Illuminate\Auth\Access\HandlesAuthorization;

/**
 * Authorization policy for Spatie Role management via Filament Shield.
 *
 * Each method delegates to the corresponding Filament Shield permission
 * (e.g., 'ViewAny:Role', 'Create:Role') which are auto-generated by the
 * shield:generate command and assigned to admin roles in RoleSeeder.
 */
class RolePolicy
{
    use HandlesAuthorization;

    /**
     * Determine if the user can view the roles list.
     *
     * @param AuthUser $authUser The authenticated user
     * @return bool True if user has the ViewAny:Role permission
     */
    public function viewAny(AuthUser $authUser): bool
    {
        return $authUser->can('ViewAny:Role');
    }

    /**
     * Determine if the user can view a specific role.
     *
     * @param AuthUser $authUser The authenticated user
     * @param Role $role The role being viewed
     * @return bool True if user has the View:Role permission
     */
    public function view(AuthUser $authUser, Role $role): bool
    {
        return $authUser->can('View:Role');
    }

    /**
     * Determine if the user can create new roles.
     *
     * @param AuthUser $authUser The authenticated user
     * @return bool True if user has the Create:Role permission
     */
    public function create(AuthUser $authUser): bool
    {
        return $authUser->can('Create:Role');
    }

    /**
     * Determine if the user can update a role.
     *
     * @param AuthUser $authUser The authenticated user
     * @param Role $role The role being updated
     * @return bool True if user has the Update:Role permission
     */
    public function update(AuthUser $authUser, Role $role): bool
    {
        return $authUser->can('Update:Role');
    }

    /**
     * Determine if the user can delete a role.
     *
     * @param AuthUser $authUser The authenticated user
     * @param Role $role The role being deleted
     * @return bool True if user has the Delete:Role permission
     */
    public function delete(AuthUser $authUser, Role $role): bool
    {
        return $authUser->can('Delete:Role');
    }

    /**
     * Determine if the user can restore a soft-deleted role.
     *
     * @param AuthUser $authUser The authenticated user
     * @param Role $role The role being restored
     * @return bool True if user has the Restore:Role permission
     */
    public function restore(AuthUser $authUser, Role $role): bool
    {
        return $authUser->can('Restore:Role');
    }

    /**
     * Determine if the user can permanently delete a role.
     *
     * @param AuthUser $authUser The authenticated user
     * @param Role $role The role being force-deleted
     * @return bool True if user has the ForceDelete:Role permission
     */
    public function forceDelete(AuthUser $authUser, Role $role): bool
    {
        return $authUser->can('ForceDelete:Role');
    }

    /**
     * Determine if the user can permanently delete any role.
     *
     * @param AuthUser $authUser The authenticated user
     * @return bool True if user has the ForceDeleteAny:Role permission
     */
    public function forceDeleteAny(AuthUser $authUser): bool
    {
        return $authUser->can('ForceDeleteAny:Role');
    }

    /**
     * Determine if the user can restore any soft-deleted role.
     *
     * @param AuthUser $authUser The authenticated user
     * @return bool True if user has the RestoreAny:Role permission
     */
    public function restoreAny(AuthUser $authUser): bool
    {
        return $authUser->can('RestoreAny:Role');
    }

    /**
     * Determine if the user can replicate a role.
     *
     * @param AuthUser $authUser The authenticated user
     * @param Role $role The role being replicated
     * @return bool True if user has the Replicate:Role permission
     */
    public function replicate(AuthUser $authUser, Role $role): bool
    {
        return $authUser->can('Replicate:Role');
    }

    /**
     * Determine if the user can reorder roles.
     *
     * @param AuthUser $authUser The authenticated user
     * @return bool True if user has the Reorder:Role permission
     */
    public function reorder(AuthUser $authUser): bool
    {
        return $authUser->can('Reorder:Role');
    }
}
